.\"
.\" Copyright (c) 2017 Paul Fariello <paul@fariello.eu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd May 11, 2017
.Dt KP_SAFE_OPEN 3
.Os
.Sh NAME
.Nm kp_safe_open
.Nd "open a safe"
.Sh LIBRARY
.Lb libkickpass
.Sh SYNOPSIS
.In kickpass/kickpass.h
.In kickpass/safe.h
.Ft kp_error_t
.Fn kp_safe_open "struct kp_ctx *ctx" "struct kp_safe *safe" "int flags"
.Sh DESCRIPTION
Open
.Fa safe .
Cleartext password and metadata are then available at safe->password and
safe->metadata.
.Pp
If an agent is available
.Fn kp_safe_open
will try to get cleartext values from the agent.
The following flags can be bitwise-or'd in
.Fa flags :
.Pp
.Bl -tag -offset indent -compact -width Dv
.It Dv KP_FORCE
Ignore agent and always get cleartext values from encrypted file.
.It Dv KP_CREATE
Ensure encrypted file doesn't exists and create new cleartext values that
can be modified afterward.
.El
.Pp
If
.Dv Bl KP_CREATE
is set
.Dv KP_FORCE
has no meaning and is therefore ignored.
.Pp
.Fn password_prompt
from
.Fa ctx
is only called if master password is absent from
.Fa ctx
and if
.Fa safe
is not stored in agent.
.Sh RETURN VALUES
Upon successful completion, the value
.Er KP_SUCCESS
is returned; otherwise any KP_* error is returned.
.Sh ERRORS
.Fn kp_safe_open
can fail with the one of the following errors:
.Bl -tag -width Er
.It Bq Er KP_EDECRYPT
Decryption error.
.It Bq Er KP_INVALID_STORAGE
Storage is invalid.
.It Bq Er KP_ERRNO
Error is specified in
.Er errno
variable.
.It Bq Er ENAMETOOLONG
Filename too long.
.It Bq Er ENOMEM
Not enough space.
.It Bq Er EACCESS
Permission denied.
.It Bq Er ENOENT
No such file or directory.
.It Bq Er EEXIST
File exists.
.El
.Sh SEE ALSO
.Xr kp_safe_delete 3 ,
.Xr kp_safe_save 3 ,
.Xr kp_safe_close 3 ,
.Xr kp_safe_get_path 3 ,
.Xr kp_safe_rename 3 ,
.Xr kp_safe_store 3
.Sh AUTHORS
.Nm
is written by
.An Paul Fariello Aq Mt paul@fariello.eu .
